CREATE TABLE IF NOT EXISTS countries
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name  VARCHAR(150) CHECK ( char_length(name) > 2 )        NOT NULL,
    code3 VARCHAR(3) CHECK ( char_length(code3) >= 3 )        NOT NULL
);

CREATE TABLE IF NOT EXISTS materials
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS mints
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255)                     NOT NULL,
    country_id BIGINT REFERENCES countries (id) NOT NULL
);

CREATE TABLE IF NOT EXISTS collections
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS coins
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)                     NOT NULL,
    description TEXT                             NOT NULL,
    "year"      SMALLINT                         NOT NULL,
    nominal     SMALLINT                         NOT NULL,
    circulation INTEGER,
    currency    VARCHAR(50)                      NOT NULL,
    country_id  BIGINT REFERENCES countries (id) NOT NULL,
    material_id BIGINT REFERENCES materials (id) NOT NULL,
    mint_id     BIGINT REFERENCES mints (id)     NOT NULL
);

CREATE TABLE IF NOT EXISTS coin_collection
(
    coin_id       BIGINT REFERENCES coins (id),
    collection_id BIGINT REFERENCES collections (id),
    PRIMARY KEY (coin_id, collection_id)
);

CREATE TABLE IF NOT EXISTS prices
(
    coin_id   BIGINT REFERENCES coins (id) NOT NULL,
    condition VARCHAR(20)                  NOT NULL,
    price     INTEGER                      NOT NULL,
    PRIMARY KEY (coin_id, condition)
);

CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1;